name: orders_employees_app
description: Aplicação Flutter para gerenciamento de pedidos e funcionários com Clean Architecture e Flutter Modular
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  amplify_flutter: ^2.5.0
  amplify_auth_cognito: ^2.5.0
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cpf_cnpj_validator: ^2.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  diacritic: ^0.1.6
  dio: ^5.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.7
  file_picker: ^8.0.7
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
  firebase_remote_config: ^4.4.7
  firebase_analytics: ^10.5.0
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.1.5
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_modular: ^6.3.4
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  http: ^1.2.2
  http_interceptor: ^2.0.0
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  loader_overlay: ^4.0.3
  lottie: ^3.1.3
  mask_text_input_formatter: ^2.9.0
  ntp: ^2.0.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  result_dart: ^1.1.1
  rive: ^0.13.20
  rsa_encrypt: ^2.0.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13
  dart_define: ^2.1.1

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

scripts:
  create_module: bash <(curl -s "https://raw.githubusercontent.com/rogeriorom/clean_arch/refs/heads/main/module_start.sh")

